Autorotate discrete
JetBrains/lets-plot pull request #1032
Opened 2024-02-29 17:04 UTC by RYangazov

2024-03-13 18:14 UTC, alshan requested changes
IMO it should be done differently.

1. There should be a function which inspect layer's geom/stat and defines if "orientation" is applicable to the layer. For example, true if stat "count", or true if geom "bar".

2. The decision about layer's orientation should be done only at the "backend", before stat is applied.

3. If concluded that orientation is "y", then add option "orientation=y" to the layer's options (see `fun replaceOwnData()` for example).

4. If only aes Y is mapped, then orientation is definitely Y.

5. If both aes - X and Y are mapped, then check whether the Y is discrete (mappings, data). And no need to combine dataframes to perform this checking. However, if X is discrete, then no need to check Y.

2024-03-26 18:00 UTC, alshan requested changes

2024-03-26 18:00 UTC, alshan commented on plot-stem/src/commonMain/kotlin/org/jetbrains/letsPlot/core/spec/config/LayerConfig.kt
> +            StatKind.BOXPLOT_OUTLIER
Is applicable to stats `YDOTPLOT`, `YDENSITY`?

2024-03-26 18:00 UTC, alshan commented on plot-stem/src/commonMain/kotlin/org/jetbrains/letsPlot/core/spec/config/LayerConfig.kt
> +            GeomKind.LOLLIPOP
`Y_DOT_PLOT` ?

2024-04-02 18:35 UTC, alshan requested changes

2024-04-02 18:35 UTC, alshan commented on plot-stem/src/commonMain/kotlin/org/jetbrains/letsPlot/core/spec/config/LayerConfig.kt
> +            setOrientationY()
This shouldn't happen if "orientation" is explicitly defined by user.

2024-04-03 19:20 UTC, RYangazov commented on plot-stem/src/commonMain/kotlin/org/jetbrains/letsPlot/core/spec/config/LayerConfig.kt
> +            setOrientationY()
If we add a check that the orientation is defined by user, the behavior does not change in any cases except when X is continuous and Y is discrete. However, it will not be possible to build a plot  using orientation="x". Now we change orientation in this case.

2024-04-04 18:07 UTC, alshan commented on plot-stem/src/commonMain/kotlin/org/jetbrains/letsPlot/core/spec/config/LayerConfig.kt
> +        if (!clientSide
Let's move initialization of `isYOrientation` variable here and put this auto-detection code in the "false" branch of the `when (hasOwn(ORIENTATION))` expression.

This way initialization of `isYOrientation` will be "atomic", in contrast to your variant where `isYOrientation get()` might be invoked before  the auto-detection code is executed.

2024-04-08 17:25 UTC, merged