Catching exception for boxplot with discrete Aes
JetBrains/lets-plot pull request #1079
Opened 2024-04-11 11:32 UTC by RYangazov

2024-04-11 18:47 UTC, alshan requested changes

2024-04-11 18:47 UTC, alshan commented on plot-base/src/commonMain/kotlin/org/jetbrains/letsPlot/core/plot/base/data/DataFrameUtil.kt
> +                "Failed to apply transform: ${transform::class.simpleName} to variable: ${variable.name}"
Let's include message from the 'cause' to this message and also pass the cause itself as the second parameter.

2024-04-12 15:51 UTC, alshan commented on plot-base/src/commonMain/kotlin/org/jetbrains/letsPlot/core/plot/base/data/DataFrameUtil.kt
> +                "Failed to apply transform: ${transform::class.simpleName} to variable: ${variable.name}"
> also pass the cause itself as the second parameter.

Do this as well pls.

2024-04-12 17:23 UTC, RYangazov commented on plot-base/src/commonMain/kotlin/org/jetbrains/letsPlot/core/plot/base/data/DataFrameUtil.kt
> +                "Failed to apply transform: ${transform::class.simpleName} to variable: ${variable.name}"
﻿To implement this, we had to remove the `e` override using `Throwables.getRootCause(e)` in `FailHandler.kt`.
Otherwise, we receive the message `Internal Error: IllegalStateException: not a collection of Double(s)`
instead of `Can't transform '..lower..' with IdentityTransform : Not a collection of Double(s)`.
It seems that this is incorrect, but there are no git-logs or comments for understanding the purpose of this line.
Could you please advise if we can remove call `getRootCause()`, or is it better to avoid passing the second parameter when generating an `IllegalArgumentException`?

2024-04-12 18:28 UTC, alshan commented on plot-base/src/commonMain/kotlin/org/jetbrains/letsPlot/core/plot/base/data/DataFrameUtil.kt
> +                "Failed to apply transform: ${transform::class.simpleName} to variable: ${variable.name}"
You are right, let's do not pass the second parameter (i.e. the cause). However, intercepting `Exception` is too broad. Since we expect an `IllegalStateException` here, let's intercept just this type.

2024-04-15 15:45 UTC, merged