size_unit and correlation matrix
JetBrains/lets-plot pull request #207
Opened 2020-09-29 12:28 UTC by IKrukov-HORIS

2020-09-29 21:41 UTC, alshan requested changes

2020-09-29 21:41 UTC, alshan commented on python-package/lets_plot/bistro/corr.py
> +    def get_format(self, format):
Use one leading underscore for non-public methods and instance variables.

2020-09-29 21:41 UTC, alshan commented on python-package/lets_plot/bistro/corr.py
> +class corr_plot_builder:
Add doc-string  to class and to public members.

2020-09-29 21:41 UTC, alshan commented on python-package/lets_plot/bistro/corr.py
> +def add_common_params(plot, reverse_y):
Let's use leading underscore in name to indicate these globals are "module non-public".

2020-09-29 21:41 UTC, alshan commented on plot-base-portable/src/commonMain/kotlin/jetbrains/datalore/plot/base/geom/PointGeom.kt
> +                val scale = getScale(ctx, p)
The name 'scale' is overused. Let's use something more concrete. What is this 'scale' anyways? Why it's depending on 'p'?

2020-09-29 21:41 UTC, alshan commented on plot-base-portable/src/commonMain/kotlin/jetbrains/datalore/plot/base/geom/TextGeom.kt
> +    var sizeUnit: String? = null
IMO all 'var'-s must be private.

2020-09-29 21:41 UTC, alshan commented on plot-base-portable/src/commonMain/kotlin/jetbrains/datalore/plot/base/geom/util/GeomHelper.kt
> +import jetbrains.datalore.plot.base.geom.PointGeom
Is this dependency necessary?

2020-09-29 21:41 UTC, alshan commented on plot-base-portable/src/commonMain/kotlin/jetbrains/datalore/plot/base/geom/util/GeomHelper.kt
> +            if ( sizeUnitName == X) {
Re-write like:
```
when (sizeUnitName.toLowerCase()) {
  "x" -> 
  "y" ->
  else -> error
```

2020-09-29 21:41 UTC, alshan commented on plot-base-portable/src/commonMain/kotlin/jetbrains/datalore/plot/base/geom/util/GeomHelper.kt
> +        const val X = "x"
remove

2020-09-29 21:41 UTC, alshan commented on plot-base-portable/src/commonMain/kotlin/jetbrains/datalore/plot/base/geom/util/GeomHelper.kt
> +            Preconditions.checkArgument(
remove

2020-09-29 21:41 UTC, alshan commented on plot-base-portable/src/commonMain/kotlin/jetbrains/datalore/plot/base/geom/util/GeomHelper.kt
> +            error("Wrong size_unit value")
more descriptive message.

2020-09-29 21:41 UTC, alshan commented on plot-config-portable/src/commonMain/kotlin/jetbrains/datalore/plot/config/GeomProtoClientSide.kt
> +                if (opts.has(Point.SIZE_UNIT)) {
Remove 'has' checking: 'getString' returns null if !has()

2020-09-29 21:41 UTC, alshan commented on plot-config-portable/src/commonMain/kotlin/jetbrains/datalore/plot/config/GeomProtoClientSide.kt
> +                    if ( sizeUnit != null) {
May be re-write as: `sizeUnit?.let {}`

2020-09-29 21:41 UTC, alshan commented on plot-config-portable/src/commonMain/kotlin/jetbrains/datalore/plot/config/GeomProtoClientSide.kt
> +                    val sizeUnit = opts.getString(Point.SIZE_UNIT)
`opts.getString(Point.SIZE_UNIT)?.toLowerCase()`

2020-09-29 21:41 UTC, alshan commented on plot-config-portable/src/commonMain/kotlin/jetbrains/datalore/plot/config/GeomProtoClientSide.kt
> +                if (opts.has(Text.SIZE_UNIT)) {
See comments for Point.SIZE_UNIT

2020-09-30 08:52 UTC, IKrukov-HORIS commented on plot-base-portable/src/commonMain/kotlin/jetbrains/datalore/plot/base/geom/TextGeom.kt
> +    var sizeUnit: String? = null
All of them represent configurable parameters and accessed from GeomProtoClientSide now. Similar way for passing parameters is used in stats. Do you propose to change this protocol?

2020-09-30 12:34 UTC, IKrukov-HORIS commented on plot-config/src/jvmTest/kotlin/plot/PlotSvgExportTest.kt
> +//
Fixed

2020-09-30 17:57 UTC, alshan requested changes

2020-09-30 17:57 UTC, alshan commented on plot-config-portable/src/commonMain/kotlin/jetbrains/datalore/plot/config/Option.kt
> +            object SizeUnit {
Pls. move`SIZE_UNIT` back to `Point`.
Only x, y should be in `SizeUnit`. `SizeUnit` itself must reside in `Geom`.
The access should look like:
Geom.Point.SIZE_UNIT
Geom.SizeUnit.X

2020-09-30 17:57 UTC, alshan commented on plot-config/src/jvmTest/kotlin/plot/PlotSvgExportTest.kt
> +//
remove

2020-09-30 17:57 UTC, alshan commented on plot-config/src/jvmTest/kotlin/plot/PlotSvgExportTest.kt
> +//    @Test
uncomment

2020-09-30 17:57 UTC, alshan commented on python-package/lets_plot/bistro/corr.py
> +        """
We are using [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard) doc-string standard. For example: For example: https://github.com/JetBrains/lets-plot/blob/2efff4cdd371a826a6718b448c1646bfdc14e1b7/python-package/lets_plot/plot/scale.py

Please, update.

2020-09-30 17:57 UTC, alshan commented on python-package/lets_plot/bistro/corr.py
> +        self._color_scale = scale_color_gradient2(name='Correlation',
Also may need to create scale_fill depending on geometries used.
Tiles - fill
Labels - color
Point - color (with the current default shape)

2020-09-30 17:57 UTC, alshan commented on plot-config-portable/src/commonMain/kotlin/jetbrains/datalore/plot/config/GeomProtoClientSide.kt
> +                    if (sizeUnit != Point.SizeUnit.X && sizeUnit != Point.SizeUnit.Y) {
We generally do not check values validity here. Let's replace this entire block with:
`geom.sizeUnit = opts.getString(Point.SIZE_UNIT)?.toLowerCase()`

2020-09-30 17:57 UTC, alshan commented on plot-config-portable/src/commonMain/kotlin/jetbrains/datalore/plot/config/GeomProtoClientSide.kt
> +                    if (sizeUnit != Text.SizeUnit.X && sizeUnit != Text.SizeUnit.Y) {
Same as Point.

2020-09-30 17:57 UTC, alshan commented on plot-base-portable/src/commonMain/kotlin/jetbrains/datalore/plot/base/geom/TextLegendKeyElementFactory.kt
> +        GeomHelper.decorate(label, p,1.0)
add space

2020-10-06 13:20 UTC, IKrukov-HORIS commented on python-package/lets_plot/bistro/corr.py
> +        """
Done

2020-10-07 14:07 UTC, closed without merging