Tooltips for geom_text, line pattern in label_fomat
JetBrains/lets-plot pull request #210
Opened 2020-10-08 12:59 UTC by OLarionova-HORIS

2020-10-08 21:39 UTC, alshan requested changes

2020-10-08 21:39 UTC, alshan commented on plot-base-portable/src/commonMain/kotlin/jetbrains/datalore/plot/base/util/StringFormat.kt
> +package jetbrains.datalore.plot.base.util
We already have some formatting-related code in 'base-portable' (NumberFormat) and in 'plot-common-portable' (text).

If StringFormat is not too plot-dependent - consider moving to ... 'base-portable' maybe?

2020-10-08 21:39 UTC, alshan commented on plot-base-portable/src/jvmTest/kotlin/plot/base/StringFormatTest.kt
> +package jetbrains.datalore.plot.base
Should be in ...base.util package.

2020-10-09 13:25 UTC, OLarionova-HORIS commented on plot-base-portable/src/commonMain/kotlin/jetbrains/datalore/plot/base/util/StringFormat.kt
> +package jetbrains.datalore.plot.base.util
StringFormat class was moved to 'base-portable'.

2020-10-09 13:31 UTC, OLarionova-HORIS commented on plot-base-portable/src/jvmTest/kotlin/plot/base/StringFormatTest.kt
> +package jetbrains.datalore.plot.base
StringFormatTest is also moved: _base-portable/src/**jvmTest**/kotlin/base/stringFormat/StringFormatTest.kt_. Is it ok?

2020-10-09 17:11 UTC, alshan commented on plot-base-portable/src/jvmTest/kotlin/plot/base/StringFormatTest.kt
> +package jetbrains.datalore.plot.base
Yes, that's fine.

2020-10-13 16:31 UTC, merged