Corr plot module
JetBrains/lets-plot pull request #220
Opened 2020-10-28 13:11 UTC by IKrukov-HORIS

2020-11-09 20:24 UTC, alshan requested changes

2020-11-09 20:24 UTC, alshan commented on python-package/lets_plot/bistro/corr.py
> +        _PLOT_PROPORTION = 3.0 / 4.0
This ratio is likely depends on presence of legend.

2020-11-09 20:24 UTC, alshan commented on python-package/lets_plot/bistro/corr.py
> +        plot += self._color_scale
'scale_color..' is not enough, tiles' use 'scale_fill..' ?

2020-11-09 20:24 UTC, alshan commented on python-package/lets_plot/bistro/corr.py
> +    def _set_diverging_palette(self, palette):
Let's rename to _set_brewer_palette.

2020-11-09 20:24 UTC, alshan commented on python-package/lets_plot/bistro/corr.py
> +                                               type='div',
Remove `type='div'`

2020-11-09 20:24 UTC, alshan commented on python-package/lets_plot/bistro/corr.py
> +        if self._tiles_layer:
Let's use API: 
```
plot = ggplot(self._data)
if self._tiles_layer:
  plot += self._tiles_layer

...
```

2020-11-10 13:33 UTC, IKrukov-HORIS commented on python-package/lets_plot/bistro/corr.py
> +        plot += self._color_scale
Tiles are implemented as point_geom with shape=15. Do we need scale_fill in this case?

2020-11-10 19:26 UTC, alshan requested changes

2020-11-10 19:26 UTC, alshan commented on python-package/lets_plot/bistro/corr.py
>          self._color_scale = scale_color_gradient2(name='Correlation',
'Correlation' takes too much space on the plot, let's call it 'Corr'.

2020-11-12 11:54 UTC, IKrukov-HORIS commented on python-package/lets_plot/bistro/corr.py
>          self._color_scale = scale_color_gradient2(name='Correlation',
Done

2020-11-23 16:12 UTC, merged