Corr plot axis tooltips
JetBrains/lets-plot pull request #254
Opened 2020-12-09 11:42 UTC by IKrukov-HORIS

- enable axis tooltips for discrete scales 
- make Y-axis tooltip align to center of target rect if tooltipKind == CURSOR_TOOLTIP
- fix tooltip visibility out of plot for tile geom
- ensure axis tooltips behaviour for univariate functions match the current release
- corrplot_matrix demo notebook fixes for latest master

2020-12-09 17:28 UTC, alshan requested changes

2020-12-09 17:28 UTC, alshan commented on plot-config-portable/src/commonMain/kotlin/jetbrains/datalore/plot/config/GeomInteractionUtil.kt
> +        return scaleMap.safeGet(aes)?.let { it.isContinuous || it.isContinuousDomain } ?: false
Isn't 'isContinuousDomain' enough? 

At any rate, 'isContinuous' means both, domain and output are continuous. Pls, simplify the condition.

2020-12-09 17:28 UTC, alshan commented on plot-builder-portable/src/jvmTest/kotlin/plot/builder/interact/GeomTargetInteractionBivariateFunctionTest.kt
> +    fun whenXIsNotContinuous_ShouldAddTooltipText() {
Consider "IsNotContinuous" -> "Discrete"

2020-12-09 17:28 UTC, alshan commented on plot-builder-portable/src/jvmTest/kotlin/plot/builder/interact/GeomTargetInteractionUnivariateFunctionTest.kt
>      fun whenPositionalNonNumericYVar_ShouldAddTooltipText() {
Consider "NonNumeric" -> "Discrete", unless there is some distinction between 'numerics as discrete' and actual non-numerical categories.

2020-12-10 08:12 UTC, IKrukov-HORIS commented on plot-config-portable/src/commonMain/kotlin/jetbrains/datalore/plot/config/GeomInteractionUtil.kt
> +        return scaleMap.safeGet(aes)?.let { it.isContinuous || it.isContinuousDomain } ?: false
I've used already existing function, it includes domain check since this: https://github.com/JetBrains/lets-plot/commit/b82ca3e16be13f3afe3f16ebefef2ca0320ce737 commit, which fixes this: https://github.com/JetBrains/lets-plot/issues/241 issue. But you are right - in this particular case it should be enough to just isContinuous property.

2020-12-10 11:44 UTC, OLarionova-HORIS commented on plot-config-portable/src/commonMain/kotlin/jetbrains/datalore/plot/config/GeomInteractionUtil.kt
> +        return scaleMap.safeGet(aes)?.let { it.isContinuous || it.isContinuousDomain } ?: false
In that example (#241) the Аes.FILL has `isContinuous = false`, but `isContinuousDomain = true`. To fix this issue we added the domain checking to the `isVariableContinuous(aes)` function.

2020-12-10 17:32 UTC, alshan commented on plot-config-portable/src/commonMain/kotlin/jetbrains/datalore/plot/config/GeomInteractionUtil.kt
> +        return scaleMap.safeGet(aes)?.let { it.isContinuous || it.isContinuousDomain } ?: false
Checking for `isContinuousDomain` would be enough then?

2020-12-10 17:46 UTC, alshan requested changes

2020-12-10 17:46 UTC, alshan commented on plot-config-portable/src/commonMain/kotlin/jetbrains/datalore/plot/config/GeomInteractionUtil.kt
> +            return scaleMap.safeGet(aes)?.let { it.isContinuous || it.isContinuousDomain } ?: false
Once again:  checking `it.isContinuous || it.isContinuousDomain` makes no sense because `it.isContinuous` is stronger condition and requires both:  domain and output are continuous.

Judging from the function name the check should be only `isContinuousDomain` (variable is the domain).

Please, make it clear for yourself and others what kind of check is needed here.

2020-12-10 17:46 UTC, alshan commented on plot-config-portable/src/commonMain/kotlin/jetbrains/datalore/plot/config/GeomInteractionUtil.kt
> +            scaleMap.safeGet(Aes.X)?.isContinuous ?: false
`isContinuous` is stronger than `isVariableContinuous()`. 

Just to make sure this is intentional.

2020-12-11 12:34 UTC, IKrukov-HORIS commented on plot-config-portable/src/commonMain/kotlin/jetbrains/datalore/plot/config/GeomInteractionUtil.kt
> +        return scaleMap.safeGet(aes)?.let { it.isContinuous || it.isContinuousDomain } ?: false
Yes, it is enough. Function is corrected.

2020-12-11 12:38 UTC, IKrukov-HORIS commented on plot-config-portable/src/commonMain/kotlin/jetbrains/datalore/plot/config/GeomInteractionUtil.kt
> +            scaleMap.safeGet(Aes.X)?.isContinuous ?: false
Changed to isVariableContinuous - it seems more suitable here.

2020-12-11 12:39 UTC, IKrukov-HORIS commented on plot-config-portable/src/commonMain/kotlin/jetbrains/datalore/plot/config/GeomInteractionUtil.kt
> +            return scaleMap.safeGet(aes)?.let { it.isContinuous || it.isContinuousDomain } ?: false
Function is corrected.

2020-12-11 18:32 UTC, alshan approved these changes

2020-12-11 18:32 UTC, merged