Updated RELEASE.md and README_PYTHON.md
JetBrains/lets-plot pull request #369
Opened 2021-05-04 09:14 UTC by VDovidaytis-HORIS

2021-05-04 16:12 UTC, alshan requested changes

2021-05-04 16:12 UTC, alshan commented on RELEASE.md
> +##### 5. Add the GitHub release:
Better: "Add the GitHub pre-release"

Also add a note:
After completing this step allow CDNJS up to 2 hours to discover and publish just released JS artifact.

2021-05-06 17:03 UTC, VDovidaytis-HORIS commented on RELEASE.md
> +##### 5. Add the GitHub release:
Done.

2021-05-06 17:19 UTC, alshan approved these changes

2021-05-06 17:19 UTC, merged