Geom violin
JetBrains/lets-plot pull request #510
Opened 2022-02-02 16:04 UTC by ASmirnov-HORIS

- Add WIDTH aesthetic.
- Add `draw_quantiles` parameter.
- Add `scale` parameter.
- Add demo for debugging.

2022-02-02 17:19 UTC, alshan requested changes

2022-02-02 17:19 UTC, alshan commented on plot-base-portable/src/commonMain/kotlin/jetbrains/datalore/plot/base/stat/YDensityStat.kt
> +        val statWidth = List(statData.getValue(Stats.X).size) { DEF_WIDTH }
What is the purpose of 'stat width' series? As we discussed the `width` aes is constant in geom_violin.

2022-02-03 09:36 UTC, ASmirnov-HORIS commented on plot-base-portable/src/commonMain/kotlin/jetbrains/datalore/plot/base/stat/YDensityStat.kt
> +        val statWidth = List(statData.getValue(Stats.X).size) { DEF_WIDTH }
Fixed.

2022-02-03 17:28 UTC, alshan approved these changes

2022-02-03 17:28 UTC, merged