New geometry - dotplot
JetBrains/lets-plot pull request #518
Opened 2022-02-17 16:46 UTC by ASmirnov-HORIS

2022-02-19 12:15 UTC, alshan requested changes

2022-02-19 12:15 UTC, alshan commented on plot-base-portable/src/commonMain/kotlin/jetbrains/datalore/plot/base/geom/DotplotGeom.kt
> +        val dotRadius = dotsize * binWidthPx
Did you mean `dotDiameter` ?

2022-02-21 11:40 UTC, IKupriyanov-HORIS commented on plot-base-portable/src/commonMain/kotlin/jetbrains/datalore/plot/base/geom/DotplotGeom.kt
> +        val dotRadius = dotsize * binWidthPx
Also `dotsize` should be `dotSize`

2022-02-21 13:47 UTC, ASmirnov-HORIS commented on plot-base-portable/src/commonMain/kotlin/jetbrains/datalore/plot/base/GeomMeta.kt
> +                Aes.WIDTH,
It affects in `computeLayerDryRunXYRangesAfterSizeExpand()`. Without `Aes.WIDTH` domain for `X` is not expaned (or I should use `BINWIDTH` aes for expansion), compare this:

![image](https://user-images.githubusercontent.com/26162403/154967204-392b9bdd-b8e1-4d05-a0be-7bde7d7714ad.png)

2022-02-22 09:29 UTC, alshan commented on plot-base-portable/src/commonMain/kotlin/jetbrains/datalore/plot/base/GeomMeta.kt
> +                Aes.WIDTH,
In this case we need to add handling of `BINWIDTH` to the `computeLayerDryRunXYRangesAfterSizeExpand()`.

2022-02-22 17:14 UTC, merged