Using clustering model for the text width estimation
JetBrains/lets-plot pull request #594
Opened 2022-09-09 10:37 UTC by ASmirnov-HORIS

2022-09-13 19:16 UTC, alshan requested changes

2022-09-13 19:16 UTC, alshan commented on plot-builder-portable/src/commonMain/kotlin/jetbrains/datalore/plot/builder/presentation/TextWidthEstimator.kt
> +            font.isBold && font.isItalic -> 0.9172120995070999
I don't understand how bold-italic style can have coefficient 0.9 and just italic - only 0.18?
Why "normal" coefficient is near 0.0?

2022-09-13 19:16 UTC, alshan commented on plot-builder-portable/src/commonMain/kotlin/jetbrains/datalore/plot/builder/presentation/TextWidthEstimator.kt
> +        val clusterId = CLUSTERS.indexOfFirst { char in it }
Let use a hash map for the symbol lookup. 
Init the hash map using elements of the `CLUSTERS` list.

2022-09-13 19:16 UTC, alshan commented on plot-builder-portable/src/commonMain/kotlin/jetbrains/datalore/plot/builder/presentation/TextWidthEstimator.kt
> +    private val CLUSTERS = listOf(
Let's add a reference on GitHub: https://github.com/ASmirnov-HORIS/text-width-estimation

2022-09-13 19:16 UTC, alshan commented on base-portable/src/commonMain/kotlin/jetbrains/datalore/base/values/FontFamily.kt
>          val MONOSPACED = forName("monospace")
Curious, does "monospace" family work. Would be nice if it does.

2022-09-14 14:32 UTC, ASmirnov-HORIS commented on plot-builder-portable/src/commonMain/kotlin/jetbrains/datalore/plot/builder/presentation/TextWidthEstimator.kt
> +            font.isBold && font.isItalic -> 0.9172120995070999
It is an additive coefficient.
So, `coeff(italic) + coeff(bold)` is approximately equal to `coeff(bold-italic)`.
And `coeff(normal)` should be zero, but it is just almost zero because of calculations (face coefficient calculated after the family coefficient).

2022-09-14 14:33 UTC, ASmirnov-HORIS commented on base-portable/src/commonMain/kotlin/jetbrains/datalore/base/values/FontFamily.kt
>          val MONOSPACED = forName("monospace")
It work.
But this particular variable is never used.

2022-09-14 14:36 UTC, ASmirnov-HORIS commented on plot-builder-portable/src/commonMain/kotlin/jetbrains/datalore/plot/builder/presentation/TextWidthEstimator.kt
> +    private val CLUSTERS = listOf(
Now I added it, but a bit higher.

2022-09-14 17:38 UTC, alshan commented on plot-builder-portable/src/commonMain/kotlin/jetbrains/datalore/plot/builder/presentation/TextWidthEstimator.kt
> +            font.isBold && font.isItalic -> 0.9172120995070999
Do you think a correction by e-17 makes any difference?

2022-09-14 19:35 UTC, alshan approved these changes

2022-09-14 19:35 UTC, merged