Fix #681 - "Variable not found" error in ggmarginal
JetBrains/lets-plot pull request #762
Opened 2023-04-13 20:13 UTC by IKupriyanov-HORIS

2023-04-13 21:14 UTC, alshan requested changes

2023-04-13 21:14 UTC, alshan commented on plot-config-portable/src/jvmTest/kotlin/plot/config/EdgeCasesTest.kt
> +    @Test
What does this have to do with "Fix #681 - "Variable not found" error in ggmarginal"?

2023-04-13 21:14 UTC, alshan commented on plot-config-portable/src/jvmTest/kotlin/plot/config/ScaleOrderingTest.kt
>  class ScaleOrderingTest {
What does scale ordering tests have to do with "Fix #681 - "Variable not found" error in ggmarginal"?

2023-04-14 13:05 UTC, IKupriyanov-HORIS commented on plot-config-portable/src/jvmTest/kotlin/plot/config/EdgeCasesTest.kt
> +    @Test
ggmarginal is not the root cause of the #681. The real issue is this - when stat is failed to apply it returns empty stats with vars that only have default mappings, missing other stat vars. 

So #681 is actually about `layer=geom_histogram()`, implicit using of the `..density..` var (that doesn't have default mapping) and empty data.
 
This test shows another, but more complex case - when data is not empty, but smooth stat still failed to apply (data points count is less than 3) and yield empty stats without the `..se..` var.

2023-04-14 13:13 UTC, IKupriyanov-HORIS commented on plot-config-portable/src/jvmTest/kotlin/plot/config/ScaleOrderingTest.kt
>  class ScaleOrderingTest {
Test expected that plot with empty data will provide scale with empty breaks. This PR changes this behaviour and now plot doesn't provide scale for empty data. So this test started to fail and it was fixed.

2023-04-14 17:20 UTC, merged