Make line width equal to point's stroke width
JetBrains/lets-plot pull request #798
Opened 2023-06-22 15:57 UTC by OLarionova-HORIS

… pointrange and lollipop.

2023-06-22 17:21 UTC, alshan requested changes

2023-06-22 17:21 UTC, alshan commented on plot-builder-portable/src/commonMain/kotlin/jetbrains/datalore/plot/builder/defaultTheme/DefaultGeomTheme.kt
>              var fill = BASE.fill
Let's get rid of the `BASE` field.

2023-06-22 17:21 UTC, alshan commented on plot-base-portable/src/commonMain/kotlin/jetbrains/datalore/plot/base/aes/AestheticsUtil.kt
> +    fun pointStrokeWidth(p: DataPointAesthetics) = AesScaling.pointStrokeWidth(p)
Why do we need `pointStrokeWidth()` when we already have `strokeWidth()` ?

2023-06-22 17:21 UTC, alshan commented on plot-builder-portable/src/commonMain/kotlin/jetbrains/datalore/plot/builder/defaultTheme/DefaultGeomTheme.kt
> +                    fill = Colors.withOpacity(inheritedColors.lineColor(), 0.1)
We don't want to use colors with opacity.

2023-06-22 17:21 UTC, alshan commented on plot-builder-portable/src/commonMain/kotlin/jetbrains/datalore/plot/builder/defaultTheme/DefaultGeomTheme.kt
>                  GeomKind.SMOOTH -> {
This is bad: `alpha = 1.5`

---
```
                GeomKind.SMOOTH -> {
                    color = Color.MAGENTA

```
We don't want to use constant values no longer. Should be a field in `BASE` (but still get rid of the `BASE`).

2023-06-26 12:58 UTC, OLarionova-HORIS commented on plot-builder-portable/src/commonMain/kotlin/jetbrains/datalore/plot/builder/defaultTheme/DefaultGeomTheme.kt
> +                    fill = Colors.withOpacity(inheritedColors.lineColor(), 0.1)
Changed to `fill` = <background color>

2023-06-26 19:38 UTC, alshan requested changes

2023-06-26 19:38 UTC, alshan commented on plot-builder-portable/src/commonMain/kotlin/jetbrains/datalore/plot/builder/defaultTheme/DefaultGeomTheme.kt
> +                    size = 0.24
Extract the experimental multiplier (1.2) to a `val` .

2023-06-28 00:30 UTC, merged